"""Crear s

Revision ID: 693b01f1fd03
Revises: 4376097d86f6
Create Date: 2025-04-26 15:32:40.456489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693b01f1fd03'
down_revision = '4376097d86f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_data', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('meta_data')

    # ### end Alembic commands ###
