"""Cres

Revision ID: cc36f45c396c
Revises: 693b01f1fd03
Create Date: 2025-04-26 16:06:28.933200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc36f45c396c'
down_revision = '693b01f1fd03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorias')
    op.drop_table('tallas')
    op.drop_table('facturas')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('nombre')

    op.drop_table('roles')
    op.drop_table('reseñas')
    op.drop_table('pedidos')
    op.drop_table('detalle_facturas')
    op.drop_table('metodos_pago')
    op.drop_table('productos')
    op.drop_table('carrito_productos')
    op.drop_table('compra_producto')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('usuarios')
    op.drop_table('carritos')
    op.drop_table('compras')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compras',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('barrio', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('observaciones', mysql.TEXT(), nullable=True),
    sa.Column('fecha_compra', mysql.DATETIME(), nullable=True),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('metodo_pago_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('estado_pedido', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodos_pago.id'], name='compras_ibfk_1'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='compras_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('carritos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('total', mysql.FLOAT(), nullable=True),
    sa.Column('estado', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name='carritos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuarios',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('num_cel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('contrasena_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('id_rol', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('reset_token', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id'], name='usuarios_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('compra_producto',
    sa.Column('compra_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', mysql.FLOAT(), nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], name='compra_producto_ibfk_1'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='compra_producto_ibfk_2'),
    sa.PrimaryKeyConstraint('compra_id', 'producto_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('carrito_productos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_carrito', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_producto', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('subtotal', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrito'], ['carritos.id'], name='carrito_productos_ibfk_1'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], name='carrito_productos_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('productos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('precio', mysql.FLOAT(), nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('id_categoria', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('imagen', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('meta_data', mysql.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id'], name='productos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('metodos_pago',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('detalle', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('detalle_facturas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_factura', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_producto', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_factura'], ['facturas.id'], name='detalle_facturas_ibfk_1'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], name='detalle_facturas_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pedidos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fecha_pedido', sa.DATE(), nullable=True),
    sa.Column('estado_pedido', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('total_pedido', mysql.FLOAT(), nullable=False),
    sa.Column('direccion_envio', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_metodo_pago', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['metodos_pago.id'], name='pedidos_ibfk_1'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name='pedidos_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reseñas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('comentario', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('calificacion', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_producto', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], name='reseñas_ibfk_1'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name='reseñas_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('nombre', ['nombre'], unique=True)

    op.create_table('facturas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_pedido', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('monto_total', mysql.FLOAT(), nullable=False),
    sa.Column('fecha_emision', mysql.DATETIME(), nullable=True),
    sa.Column('estado', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id'], name='facturas_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tallas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('categoria_talla', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categorias',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
