"""Creas

Revision ID: f29a94ef12d6
Revises: 90929b02dfb4
Create Date: 2025-04-23 10:31:15.236591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29a94ef12d6'
down_revision = '90929b02dfb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_pedido', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_column('estado_pedido')

    # ### end Alembic commands ###
